# Matching in Surveys {.unnumbered}

## Video content

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/SUjo2bWrfZ8" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

## Slides

[Download](https://github.com/ehsanx/PS-survey/raw/main/slides/4Propensityscorematchingwithinsurveys.pdf)

## Summary of topics discussed

### Tabular summary

| Approach                            | PS Model: Use of Design Variables                                                                                                                                                                                                      | Outcome Model: Use of Design Variables                                               |
|----------------|--------------------------|------------------------------|
| Zanutto (2006)                      | Not necessary in PS estimation                                                                                                                                                                                                         | Incorporate survey design features (weight+cluster+strata) in the outcome regression |
| DuGoff et al. (2014)                | Include as predictors                                                                                                                                                                                                                  | Include weight+cluster+strata for PATT; cluster+strata for SATT                      |
| Austin et al. (2018)                | Use while estimating PS                                                                                                                                                                                                                | Use survey features for population inferences                                        |
| Lenis et al. (2017)                 | Does not affect matching estimator performance                                                                                                                                                                                         | Must use design features for population estimates                                    |
| Reasonable approach (my suggestion) | Use if it provides best balance (e.g., measured by SMD). Often applying design features in the PS estimation is not possible due to the shortcoming of the software available for the machine learning approach chosen to estimate PS. | Must use all design features for population estimates                                |

### References (Optional)

1.  Zanutto, E. L. (2006). [A comparison of propensity score and linear regression analysis of complex survey data](https://jds-online.org/journal/JDS/article/1052/info). Journal of data Science, 4(1), 67-91.
2.  DuGoff, E. H., Schuler, M., & Stuart, E. A. (2014). [Generalizing observational study results: applying propensity score methods to complex surveys](https://pubmed.ncbi.nlm.nih.gov/23855598/). Health services research, 49(1), 284-303.
3.  Lenis, D., Nguyen, T. Q., Dong, N., & Stuart, E. A. (2017). [It's all about balance: propensity score matching in the context of complex survey data](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6296318/). Biostatistics. 2019 Jan; 20(1): 147--163.
4.  Austin, P. C., Jembere, N., & Chiu, M. (2018). [Propensity score matching and complex surveys](https://pubmed.ncbi.nlm.nih.gov/27460539/). Statistical methods in medical research, 27(4), 1240-1257.
